const texts={
et:{services:'Teenused',about:'Meist',contacts:'Kontaktid',book:'Broneeri',tag:'Täpsus. Hoolivus. Tulemus.',serviceTitle:'Meie teenused',serviceLead:'Kaasaegne hambaravi, mis on kavandatud teie tervise, mugavuse ja kindla naeratuse jaoks.',c1:'Kaariese ravi',c1d:'Õrn ja täpne ravi kaasaegsete materjalide ning mikroskoobi abil.',c2:'Ennetus',c2d:'Professionaalne puhastus ja personaalne plaan terve naeratuse hoidmiseks.',c3:'Ortodontia',c3d:'Läbipaistvad kaped ja täpne digitaalne planeerimine igas vanuses patsiendile.',i1:'Kaariese ravi ja hammaste taastamine kaasaegsete materjalidega.',i2:'Ennetavad protseduurid hammaste tervise säilitamiseks.',i3:'Ortodontiline ravi: breketid, kaped ja hambumuse korrigeerimine.',aboutTitle:'Meist',aboutLead:'Oleme futuristlik hambakliinik AI-diagnostika ja Euroopa kvaliteediga seadmetega.',aboutText:'FTORDENT ühendab meditsiinilise kogemuse, digitaalse diagnostika ja hooliva suhtumise. Selgitame iga sammu arusaadavalt ning leiame teie jaoks sobiva raviplaani.',s1:'digitaalne diagnostika',s2:'tark raviplaneerimine',s3:'terviklik hooldus',s4:'isiklik lähenemine',contactTitle:'Kontaktid',address:'Narva, Rahu 34a'},
en:{services:'Services',about:'About us',contacts:'Contacts',book:'Book now',tag:'Precision. Care. Results.',serviceTitle:'Our services',serviceLead:'Modern dental care designed for your health, comfort and a confident smile.',c1:'Cavity treatment',c1d:'Gentle, precise treatment with modern materials and a microscope.',c2:'Prevention',c2d:'Professional cleaning and a personal plan for a healthy smile.',c3:'Orthodontics',c3d:'Clear aligners and precise digital planning for patients of every age.',i1:'Cavity treatment and tooth restoration with modern materials.',i2:'Preventive procedures to preserve dental health.',i3:'Orthodontic treatment: braces, aligners and bite correction.',aboutTitle:'About us',aboutLead:'We are a forward-looking dental clinic with AI diagnostics and European-grade equipment.',aboutText:'FTORDENT combines clinical experience, digital diagnostics and attentive care. We explain every step clearly and create a treatment plan that is right for you.',s1:'digital diagnostics',s2:'smart treatment planning',s3:'complete care',s4:'personal approach',contactTitle:'Contacts',address:'Narva, Rahu 34a'},
ru:{services:'Услуги',about:'О нас',contacts:'Контакты',book:'Записаться',tag:'Точность. Забота. Результат.',serviceTitle:'Наши услуги',serviceLead:'Современная стоматология для здоровья, комфорта и уверенной улыбки.',c1:'Лечение кариеса',c1d:'Бережное и точное лечение современными материалами и под микроскопом.',c2:'Профилактика',c2d:'Профессиональная чистка и персональный план для здоровой улыбки.',c3:'Ортодонтия',c3d:'Прозрачные элайнеры и точное цифровое планирование для пациентов любого возраста.',i1:'Лечение кариеса и восстановление зубов современными материалами.',i2:'Профилактические процедуры для сохранения здоровья зубов.',i3:'Ортодонтическое лечение: брекеты, капы и исправление прикуса.',aboutTitle:'О клинике',aboutLead:'Мы — футуристическая стоматологическая клиника с AI-диагностикой и европейским оборудованием.',aboutText:'FTORDENT объединяет медицинский опыт, цифровую диагностику и внимательное отношение. Мы понятно объясняем каждый этап и подбираем план лечения именно для вас.',s1:'цифровая диагностика',s2:'умное планирование лечения',s3:'комплексная забота',s4:'личный подход',contactTitle:'Контакты',address:'Нарва, Раху 34а'}};
let lang=localStorage.getItem('ftordent-language')||'et';
function setLang(next){lang=next;localStorage.setItem('ftordent-language',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(e=>e.textContent=texts[lang][e.dataset.t]);document.querySelectorAll('.lang').forEach(e=>e.classList.toggle('active',e.dataset.lang===lang));}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(lang);
document.querySelectorAll('.card[data-info]').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.card').forEach(c=>c.classList.remove('active'));card.classList.add('active');document.querySelector('#service-info').textContent=texts[lang][card.dataset.info]}));
const quickText={et:{title:'Broneeri aeg',name:'Teie nimi',phone:'Telefon',day:'Soovitud päev',send:'Saada päring'},en:{title:'Book an appointment',name:'Your name',phone:'Phone',day:'Preferred day',send:'Send request'},ru:{title:'Записаться на приём',name:'Ваше имя',phone:'Телефон',day:'Желаемый день',send:'Отправить заявку'}};
if(!location.pathname.endsWith('booking.html')){const quick=document.createElement('dialog');quick.style.cssText='border:1px solid #08e5df;border-radius:24px;color:#f5f4ec;background:#11194a;width:min(460px,calc(100% - 32px));box-shadow:0 0 80px rgba(0,218,247,.32)';document.body.append(quick);function showQuick(){const t=quickText[lang];quick.innerHTML='<div style="display:flex;justify-content:space-between;align-items:start"><h2 style="margin:0">'+t.title+'</h2><button type="button" style="background:none;border:0;color:white;font-size:26px;cursor:pointer" aria-label="Close">×</button></div><form style="display:grid;gap:14px;margin-top:22px"><input required name="name" placeholder="'+t.name+'" style="padding:14px;border-radius:12px;border:1px solid #b3d4ff;background:#ffffff14;color:white"><input required name="phone" type="tel" placeholder="'+t.phone+'" style="padding:14px;border-radius:12px;border:1px solid #b3d4ff;background:#ffffff14;color:white"><input required name="day" type="date" min="'+new Date().toISOString().slice(0,10)+'" style="padding:14px;border-radius:12px;border:1px solid #b3d4ff;background:#ffffff14;color:white"><button style="border:0;border-radius:999px;padding:14px;background:linear-gradient(100deg,#08e5df,#18a9ff);font-weight:800;cursor:pointer" type="submit">'+t.send+'</button></form>';quick.querySelector('button[type="button"]').onclick=()=>quick.close();quick.showModal();}document.querySelectorAll('a.book').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showQuick();}));}
document.querySelectorAll('a.book').forEach(b=>b.setAttribute('href','#booking'));

